fix: ipv6 ident
kilo-io/iptables_parser pull request #11
Opened 2024-02-12 14:12 UTC by MEschenbacher

Resolves #10

2024-02-12 14:25 UTC, leonnicolas reviewed
Thanks a lot. Can you please add a test where an IPv6 address starts with `::`. I think that should be possible in theory.

And also the `(d *DNSOrIP) Set(s string)` in https://github.com/kilo-io/iptables_parser/blob/275b7c93e8a7588940a64c72b9ba462d254ba1bc/parser.go#L209
is still just blindly adding a `/32`. I think we just resolve that with this PR to prevent an IPv6 address from being parsed with a `32` network mask. Maybe we can use https://cs.opensource.google/go/go/+/go1.22.0:src/net/ip.go;l=494 if there is no network mask and then https://cs.opensource.google/go/go/+/go1.22.0:src/net/ip.go;l=52 to find out if it is v4 or v6 and adding the suffix accordingly. wdyt?

Also a test where we parse a complete rule that contains an IPv6 address would increase my confidence a lot. Let me know if I can help you with anything!

2024-02-12 14:49 UTC, MEschenbacher commented
Yes sounds all good, will do :)

2024-02-12 14:58 UTC, leonnicolas commented
I think IP.IPv4 is not part of go version 1.16, but we can update it. I the only places are in go.mod and the github action file

2024-02-16 12:31 UTC, MEschenbacher commented
I've added three more commits to implement/fix issues, however solving the one issue at hand, regarding extending `COLON` to decide whether this is a `COLON` or `IDENT` is not as easy as I thought.

2024-02-20 08:45 UTC, leonnicolas reviewed
I think the `COMMIT` and "no counter" commits should be in separate PRs. This way we can merge the IPv6 support quickly and not block it by my slow reviews.

2024-02-20 08:45 UTC, leonnicolas commented on parser.go
> +type Commit struct{}
Can you make a separate PR for this?

2024-03-29 07:20 UTC, MEschenbacher commented on parser.go
> +type Commit struct{}
Done :)

2024-03-30 13:39 UTC, leonnicolas requested changes
Thanks very much. I think everything is fine with me. Can you rebase from our main branch first? I see some changes in this PR, that are already in our main branch.

2024-03-30 13:39 UTC, leonnicolas commented on .github/workflows/test.yaml
> +  fmt:
thanks

2024-03-30 13:39 UTC, leonnicolas commented on .github/workflows/test.yaml
> +      - uses: actions/setup-go@v1
I think if we already touched this, we can update the actions/setup-go version
```suggestion
      - uses: actions/setup-go@v5
```

2024-03-30 13:39 UTC, leonnicolas commented on LICENSE
> +Copyright (c) 2022 Leon Löchner
```suggestion
Copyright (c) 2024 Leon Löchner
```

2024-03-30 13:39 UTC, leonnicolas commented on README.md
> +[![Documentation](https://godoc.org/github.com/kilo-io/iptables_parser?status.svg)](http://godoc.org/github.com/kilo-io/iptables_parser)
thanks

2024-03-30 13:39 UTC, leonnicolas commented on parser.go
> +		return nil, io.EOF // ErrEOF
```suggestion
		return nil, io.EOF
```

2024-03-30 13:39 UTC, leonnicolas commented on parser.go
> -func (p *Parser) unscanIgnoreWhitespace(n int) error {
right, we never use that. There are some comments that mention this method. I can make a follow up to remove those confusing comments.

2024-03-30 13:39 UTC, leonnicolas commented on parser_test.go
> +			s:    "-A foo ! -s 192.168.178.2 ! --dst 1.1.1.1 -m statistic --mode random --probability 0.50000000000 --every 10 --packet 5",
hmm this is a bit funny. Now, rules that have a probability of 0.5 are different from rules with 0.50.

I wonder if we can do anything about that?

2024-03-30 13:39 UTC, leonnicolas commented on parser_test.go
> +		t.Run(tc.name, func(t *testing.T) {
nice

2024-03-30 13:39 UTC, leonnicolas commented on targets.go
> +	case "SNAT":
i think you need to rebase from our main branch. Your branch is behind

2024-03-31 12:06 UTC, leonnicolas approved these changes

2024-03-31 12:07 UTC, merged